# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[(b'art', b'Art'), (b'audio', b'Audio'), (b'writing', b'Writing')], max_length=50)),
            ],
        ),
    ]
