# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 22:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160114_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[(b'art', b'Art'), (b'audio', b'Audio'), (b'writing', b'Writing')], default=b'open', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='date',
            field=models.DateField(auto_now=True, default=datetime.datetime(2016, 1, 14, 22, 52, 45, 12000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 1, 14, 22, 53, 2, 635000, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[(b'open', b'open'), (b'in_progress', b'In progress'), (b'done', b'Done'), (b'to_be_deleted', b'To be deleted')], default=b'open', max_length=50),
        ),
    ]
