# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 22:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160114_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='notes',
            field=models.CharField(blank=True, default=datetime.datetime(2016, 1, 14, 22, 54, 18, 718000, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
