# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20160114_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[(b'art', b'Art'), (b'audio', b'Audio'), (b'writing', b'Writing')], default=b'art', max_length=50),
        ),
    ]
